//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCT
    {
        public int MaCT_BCT { get; set; }
        public int MaBaoCaoTon { get; set; }
        public Nullable<int> TonDau { get; set; }
        public Nullable<int> TonCuoi { get; set; }
        public int MaDauSach { get; set; }
        public Nullable<int> NhapVao { get; set; }
        public Nullable<int> BanRa { get; set; }
    
        public virtual BAOCAOTON BAOCAOTON { get; set; }
        public virtual DAUSACH DAUSACH { get; set; }
    }
}
