//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCCN
    {
        public int MaCT_BCCN { get; set; }
        public int MaBaoCaoCongNo { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<decimal> NoDau { get; set; }
        public Nullable<decimal> NoCuoi { get; set; }
        public Nullable<decimal> NoMoi { get; set; }
        public Nullable<decimal> DaThu { get; set; }
    
        public virtual BAOCAOCONGNO BAOCAOCONGNO { get; set; }
    }
}
