//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HD
    {
        public int MaCT_HD { get; set; }
        public int MaHoaDon { get; set; }
        public int MaSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
