//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using BookStore.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DAUSACH:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAUSACH()
        {
            this.SACHes = new HashSet<SACH>();
            this.TACGIAs = new HashSet<TACGIA>();
            this.THELOAIs = new HashSet<THELOAI>();
        }
    
        public int MaDauSach { get; set; }
        private string _TenSach;
        private Nullable<int> _LuongTon;
        public byte[] HinhAnhSach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SACH> SACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACGIA> TACGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THELOAI> THELOAIs { get; set; }
        public string TenSach { get => _TenSach; set { _TenSach = value; OnPropertyChanged(); } }
        public int? LuongTon { get => _LuongTon; set { _LuongTon = value; OnPropertyChanged(); } }
    }
}
