//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhSach
    {
        public int MaHinhAnh { get; set; }
        public int MaDauSach { get; set; }
        public string DuongDan { get; set; }
    }
}
