//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CT_HD = new HashSet<CT_HD>();
        }
    
        public int MaHoaDon { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayLapHoaDon { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> SoTienTra { get; set; }
        public Nullable<decimal> ConLai { get; set; }
        public int MaNguoiLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HD> CT_HD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
