//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIEN
    {
        public int MaPhieuThuTien { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayThuTien { get; set; }
        public Nullable<decimal> SoTienThu { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
