//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int MaThamSo { get; set; }
        public Nullable<int> LuongNhapToiThieu { get; set; }
        public Nullable<int> LuongTonToiThieu { get; set; }
        public Nullable<decimal> SoNoToiDa { get; set; }
        public Nullable<int> LuongTonToiThieuSauBan { get; set; }
        public Nullable<bool> ChoPhepThuLonHonNo { get; set; }
    }
}
